name: ccrr
version: '${version}'
main: com.kenjietsu.ccr.Ccr
api-version: '1.18'
depend: ['Multiverse-Core']
commands:
    ccr:
        description: 'start game'
        usage: /<command>
        permission: ccrr.command.ccr
        aliases: [ccr]
    ccrestart:
        description: 'restart game'
        usage: /<command>
        permission: ccrr.command.ccrestart
        aliases: [ccrestart]
    ccaddnonplayer:
        description: 'add nonplayer'
        usage: /<command>
        permission: ccrr.command.ccaddnonplayer
        aliases: [ccaddnonplayer]
    CCRGallinita:
        description: 'give gallinita'
        usage: /<command>
        permission: ccrr.command.CCRGallinita
        aliases: [CCRGallinita]
    CCAote:
        description: 'give aote'
        usage: /<command>
        permission: ccrr.command.CCRAote
        aliases: [CCRAote]
    CCTimer:
        description: 'start timer'
        usage: /<command>
        permission: ccrr.command.CCTimer
        aliases: [CCTimer]
    CCTester:
        description: 'test command'
        usage: /<command>
        permission: ccrr.command.CCTester
        aliases: [CCTester]
    CCRanswer:
        description: 'answer command'
        usage: /<command>
        permission: ccrr.command.CCRanswer
        aliases: [ccranswer]
    CCSpeed:
        description: 'set speed'
        usage: /<command>
        permission: ccrr.command.CCSpeed
        aliases: [ccspeed]
    CCSacrificar:
        description: 'sacrificar'
        usage: /<command> <player>
        permission: ccrr.command.CCSacrificar
        aliases: [ccsacrificar]
permissions:
    ccrr.command.CCRanswer:
        description: 'answer command'
        default: true